apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uah5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-uah5@sha256:0cee20524ebfd52c579865fca9f06d02e55034cc1c313faca58a6c5e8775d1ae
        name: my-nodejs
        resources: {}
status: {}
